#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

start_service() {
	[ "$(uci -q get openlist-qos.main.enabled)" = "1" ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/openlist-qos daemon
	procd_set_param respawn 5 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	/usr/sbin/openlist-qos remove
}

reload_service() {
	stop
	start
}
